### ISSUE TITLE
Unstashing binary report "ERROR SYS VER"

### ISSUE THREAD

**Issue by palxex** [coolstar/stash933#2]
Binary: https://coolstar.org/SemiRestore-10Lite, as mentioned in reddit.md5 c716027bcf41d632bac60e0051303010
My environment: iPad Air, iOS 10.2, yalu latest commit
uname -a: Darwin iPad 16.3.0 Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:09 PST 2016; root:xnu-3789.32.1~4/MarijuanARM64_S5L8960X iPad4,1 arm64 J71AP Darwin
Suggest: It would be better if a script version could be included in the package.

**Comment by coolstar** [comment]
SemiRestore10-Lite is a separate project.

**Comment by palxex** [comment]
@coolstar  could you give me where should I report the problem for SemiRestore10-Lite?
